import Link from "next/link";
import { ArrowLeft, Crown, Trophy } from "lucide-react";
import { HeritageDirectory } from "@/components/heritage-directory";
import { PlayerProgress } from "@/components/player-progress";
import { getAllHeritage } from "@/lib/heritage";

export default function RoyaumesPage() {
  const kings = getAllHeritage().filter((item) => item.type === "roi").sort((a, b) => a.nom.localeCompare(b.nom, "fr"));
  return <main className="min-h-screen bg-earth px-5 py-5 text-kaolin sm:px-8 sm:py-8"><div className="mx-auto w-full max-w-6xl"><header className="flex items-center justify-between gap-4"><Link href="/" className="group flex items-center gap-3 rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold"><span className="grid size-11 place-items-center rounded-full border border-gold/45 bg-gold/10 text-gold"><Trophy aria-hidden="true" size={21} /></span><span className="font-display text-lg text-white">GAGNANTS 229</span></Link><PlayerProgress /></header><Link href="/explorer" className="mt-9 inline-flex min-h-11 items-center gap-2 text-sm font-bold text-kaolin/70 transition hover:text-gold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold"><ArrowLeft aria-hidden="true" size={17} /> Retour aux collections</Link><section className="mt-5 rounded-3xl border border-gold/25 bg-panel p-6 shadow-[0_24px_80px_rgba(0,0,0,0.28)] sm:p-9"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-gold"><Crown aria-hidden="true" size={16} /> Gamme 02 · Royaumes & Histoire</p><h1 className="font-display mt-3 text-4xl leading-tight text-white sm:text-5xl">Rois, reines et mémoires du Bénin</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-kaolin/75 sm:text-base">Choisis une figure pour ouvrir son récit. Les fiches en préparation sont déjà accessibles : tu pourras les enrichir dans le fichier de données.</p><HeritageDirectory items={kings} label="Royaumes & Histoire" /></section></div></main>;
}
